### ISSUE TITLE
请教，编译后效果，设置里无“线程数”与“后台思考”两项

### ISSUE THREAD

**Issue by fsssosei** [dhbloo/gomoku-calculator#1]
同一个浏览器开官网的计算器，设置里就看到有“线程数”与“后台思考”
我编译的出来的就没有
是为啥呢
我看settings.js里有呀

**Comment by dhbloo** [comment]
目前的浏览器要求网站满足一定的要求才能开启多线程。
请参考[Deployment说明](https://github.com/dhbloo/gomoku-calculator#deployment)配置网站的COEP header和`dist/build`文件夹下的所有wasm文件的MIME type。

**Comment by fsssosei** [comment]
谢谢解答。完成设置了
