### ISSUE TITLE
website gomocalc.com offline

### ISSUE THREAD

**Issue by DonLeeFK** [dhbloo/gomoku-calculator#3]
Hi, I've been using the online gomoku calculator for a while and I assume it's this project. I thank you for your amazing work on this project. 

The website http://gomocalc.com is offline now apparently, will you consider re launching it or do I have to build this project myself?

**Comment by AnnAngela** [comment]
Documents include some mirror sites that you can have a try: <https://github.com/dhbloo/gomoku-calculator/blob/master/src/views/About-en.md#about-the-app>

**Comment by dhbloo** [comment]
Hi, 

As described in the announcement, you can visit these two mirror sites when gomocalc.com is offline:
+ https://gobang.varpop.com
+ https://wzq.xiangqiai.com

Both sites have the same functionality as the main site.

gomocalc.com will return in a few weeks, after maintenance and update.

**Comment by dhbloo** [comment]
https://gomocalc.com is now back online :)
